### ISSUE TITLE
Make a diecision about using virtualenv

### ISSUE THREAD

**Issue by mbiokyle29** [mbiokyle29/geno-browser#2]
We should diecide if we want to have a virtualenv for python/flask in the repo. 
Otherwise we need to get some kind of dependency management going for the python side of things.

**Comment by CodaP** [comment]
We will probably use virtualenv in production, but we don't need to decide on that ever. Anything we make should run on reasonably recent versions of all libraries. So to each developer his own, if you write something that works and breaks between minor versions you should rewrite it with something more maintainable. Personally I use [Anaconda](http://continuum.io/downloads) python as a package manager and it does support environments like virtualenv. It is designed for scientific python and handles binaries really well. But if you want to use apt-get that should be fine.
