### ISSUE TITLE
core.py was deleted in api branch

### ISSUE THREAD

**Issue by CodaP** [mbiokyle29/geno-browser#4]
and things broke.

**Comment by mbiokyle29** [comment]
What things broke?
And are you working on the api branch?

**Comment by CodaP** [comment]
There is an import for it in __init__.py and models. Did you delete core.pyc too?
I'm not working on the api branch.

**Comment by mbiokyle29** [comment]
I changed the import in **init**, and I just got the one in models, thanks for the reminder. 
As for the pyc file that shouldnt even in source control should it?
And I havent pushed any of this changes out of the api branch, so why is this an issue?
